# docker-compose.yml
version: '3.8'

services:
  backend:
      build:
        context: .
        dockerfile: ./backend.Dockerfile
      ports:
        - "80:8081"
      env_file:
        - .env
  prisma-studio:
    build:
      context: .
      dockerfile: ./prisma.Dockerfile
    ports:
      - "80:5555"
    env_file:
      - .env
  prisma-migrate:
    container_name: prisma-migrate
    build: 
      context: .
      dockerfile: ./prisma-migrate.Dockerfile
    env_file:
      - .env