version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sixte
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      dbnet:
        ipv4_address: 172.25.0.4

  prisma-migrate:
    container_name: prisma-migrate
    build: 
      context: .
      dockerfile: ./prisma-migrate.Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@172.25.0.4:5432/sixte?schema=public
    depends_on:
      - db
    networks:
      dbnet:
        ipv4_address: 172.25.0.6

  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/workspace
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@172.25.0.4:5432/sixte?schema=public
      - MODE=prod
    networks:
      dbnet:
        ipv4_address: 172.25.0.5

  prisma-studio:
    build:
      context: .
      dockerfile: ./prisma.Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@172.25.0.4:5432/sixte?schema=public
    networks:
      dbnet:
  
volumes:
  db_data:

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
